# Generated by Django 4.2 on 2023-05-15 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadasrtroCliente', '0009_cliente_interesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Ativo',
            field=models.BooleanField(verbose_name='Usuário Ativo?'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=250, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='matricula',
            field=models.IntegerField(verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nro',
            field=models.CharField(max_length=7, null=True, verbose_name='N°'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='profissao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CadasrtroCliente.profissao', verbose_name='Profissões'),
        ),
    ]
